ElectronicSignatureDocumentViewer/Models/SignatureData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ElectronicSignatureDocumentViewer.Models
{
    public class SignatureData
    {
        public string Barcode { get; set; }
        public string Signer { get; set; }
        public string IPAddress { get; set; }
    }
}

ElectronicSignatureDocumentViewer/Controllers/HomeController.cs
using ElectronicSignatureDocumentViewer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElectronicSignatureDocumentViewer.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            SignatureData data = new SignatureData()
            {
                Barcode = "https://www.textcontrol.com/",
                IPAddress = "102.72.278.0",
                Signer = "Tim Typer"
            };

            return View(data);
        }

        public ActionResult Thanks()
        {
            return View();
        }
    }
}

ElectronicSignatureDocumentViewer/Controllers/SignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElectronicSignatureDocumentViewer.Controllers
{
    public class SignController : Controller
    {
        [HttpPost]
        public string ExportPDF(string document)
        {
            byte[] bPDF;

            // create temporary ServerTextControl
            using (TXTextControl.ServerTextControl tx = new TXTextControl.ServerTextControl())
            {
                tx.Create();

                // load the document
                tx.Load(Convert.FromBase64String(document), TXTextControl.BinaryStreamType.InternalUnicodeFormat);

                TXTextControl.SaveSettings saveSettings = new TXTextControl.SaveSettings()
                {
                    CreatorApplication = "TX Text Control Sample Application",
                };

                // save the document as PDF
                tx.Save(out bPDF, TXTextControl.BinaryStreamType.AdobePDF, saveSettings);
            }

            // return as Base64 encoded string
            return Convert.ToBase64String(bPDF);
        }
    }
}

ElectronicSignatureDocumentViewer/Views/Home/Index.cshtml
@model ElectronicSignatureDocumentViewer.Models.SignatureData
@using TXTextControl.Web.MVC.DocumentViewer

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@Html.TXTextControl().DocumentViewer(settings =>
{
    settings.DocumentPath = Server.MapPath("~/App_Data/contract.tx");
    settings.Dock = DocumentViewerSettings.DockStyle.Window;
    settings.IsSelectionActivated = true;
    settings.ShowThumbnailPane = true;
    settings.SignatureSettings = new SignatureSettings()
    {
        OwnerName = "Paul Paulsen",
        SignerName = Model.Signer,
        ShowSignatureBar = true,
        UniqueId = Guid.NewGuid().ToString(),

        CustomSignatureData = new ElectronicSignatureDocumentViewer.Models.SignatureData()
        {
            Barcode = Model.Barcode,
            Signer = Model.Signer,
            IPAddress = Model.IPAddress
        }
    };
}).Render()

<script>
    // set the callback method after submit
    window.addEventListener("documentViewerLoaded", function () { TXDocumentViewer.setSubmitCallback(exportPDF) });

    function exportPDF(e) {
        var serviceURL = "@Url.Action("ExportPDF", "Sign")";

        console.log(e);

        // send document to controller
        $.ajax({
            type: "POST",
            url: serviceURL,
            data: {
                document: e.document
            },
            success: successFunc,
            error: errorFunc
        });
    }

    function successFunc(data, status) {

        // create temporary link to download document
        var element = document.createElement('a');
        element.setAttribute('href', 'data:application/octet-stream;base64,' + data);
        element.setAttribute('download', "result.pdf");

        element.style.display = 'none';
        document.body.appendChild(element);

        // simulate click
        element.click();

        // remove the link
        document.body.removeChild(element);

        window.location = "/Home/Thanks"
    }

    function errorFunc() {
        alert("Error");
    }
</script>

ElectronicSignatureDocumentViewer/Views/Home/Thanks.cshtml
@{
    ViewBag.Title = "Thanks";
}

<h2>Thanks for signing!</h2>

ElectronicSignatureDocumentViewer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document Signing Sample</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />

    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    </head>
<body>

    @RenderBody()

    <script src="~/lib/twitter-bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/jquery.min.js"></script>
</body>
</html>